### ISSUE TITLE
refresh the page is always need?

### ISSUE THREAD

**Issue by alexwel** [vsevolodts/TimeIT.js#2]
Hi, I have a question about TimeIT.js I am using it for a project, I am wondering is there any way to make the script execute without need of reloading page? as an example if I set the time to 09:00 in I enter the page 08:55 and keep the page open when the clock passes 09:00 the content is still shown in tell i do to refresh is the any what to hide the div with out a need to refresh the page when it passes the ended time

**Comment by vsevolodts** [comment]
Hi Alex, 
Thank you for the suggestion; I will improve the script in early December to allow binding. As a quick fix you can just call the function when you need (onclick, or [every minute](http://stackoverflow.com/questions/13304471/javascript-get-code-to-run-every-minute))

**Comment by alexwel** [comment]
Hi, Great thanks for the link. One more question is it possible to set the intervals of repeat in minutes and not just per hour per day? The problem i am having is if i have something that need to repeat 4 times on every hour everyday i have to make 96 div entries with data-start and data-end of the same content

**Comment by vsevolodts** [comment]
Hi Alex;
I've add the update functionality to the script, so the content will be updated without the page reload on time of the next event.

As of multiple repeats: I need to think how to supply multiple intervals to the evaluation script.

Can you please explain (an provide a piece of code) where you have issues with an interval in minutes?
The data-input field is supporting minutes now; for example:
`<li data-start="12:00" data-end="12:15" class="timeit">display data after noon for 15 minutes</li>`

Do you want something like this?
`<li data-start=":00" data-end=":15" class="timeit">for 15 minutes every hour</li>`

As I understood the issue, the easiest way to solve will be to supply current hour on a server side.

**Comment by vsevolodts** [comment]
Closing the issue; the request is transferred to a new topic
