### ISSUE TITLE
Firefox says date is an error

### ISSUE THREAD

**Issue by cadams7** [vsevolodts/TimeIT.js#3]
"2017-01-24 23:59" date is incorrect; please use YYYY-MM-DD HH:MM format

Any ideas? Working fine on other browsers.

**Comment by cadams7** [comment]
Seeing it in older IE also, updating firefox helped. Looks limited to older browsers.

**Comment by vsevolodts** [comment]
Thank you for reporting the issue. I will check the code in older browsers

**Comment by cadams7** [comment]
Thanks!

**Comment by vsevolodts** [comment]
fixes with v3
