### ISSUE TITLE
Mobile Browser Issue

### ISSUE THREAD

**Issue by sburkeen** [vsevolodts/TimeIT.js#4]
Hi, thank you for the script. This is exactly what I have been searching for. I have noticed that mobile browsers (iPhone 6s plus Safari and Chrome) are not obeying the hidden class. I've even tried inserting custom CSS to change .hidden to display none. Is this an issue with how the JavaScript pulls time from a mobile browser?

**Comment by vsevolodts** [comment]
Hi, the script is compatible with every browser/platform that support CSS and Javascript.
Please access the demo page http://codegen.in/timeit/ using your device to confirm the error.
